name: cpd_test_app
description: Codex 학습용 로컬 SQLite 게시판 앱입니다.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  path: ^1.9.0
  sqflite: ^2.3.3

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  sqflite_common_ffi: ^2.3.3

flutter:
  uses-material-design: true
